### ISSUE TITLE
Throws error unhandled stream error in pipe when do npm install offline

### ISSUE THREAD

**Issue by Arch-Mage** [nolanlawson/local-npm#101]
I tried to disconnect the internet connection and leave `local-npm` server
running. Then, I do `npm install` it gives me:

    stream.js:74
          throw er; // Unhandled stream error in pipe.
          ^

    Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
        at errnoException (dns.js:26:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

And then the process exited.

The listed packages on `package.json` is already stored locally. Because, before I run `npm install` offline,
I installed everything first and `local-npm` say this:

    downloaded koa at version 2.0.0-alpha.3 and saved it locally
and some other things

It supposed to work offline, right?

**Comment by nolanlawson** [comment]
Yes, this looks like a bug. Sorry about that.

Unfortunately I can't reproduce - which version of `local-npm` are you using?

**Comment by nolanlawson** [comment]
Nevermind, I can reproduce. The error is the one described in the README:

> Note that new tarballs aren't downloaded until you explicitly `npm install` them, though. So e.g. if you install `v1.0.0` of a package, then `v1.0.1` is published, and your range says `^1.0.0`, then the next `npm install` will fail unless you're online and can fetch the new tarball.

So e.g. when I reproduced this, I saw in the logs:

    node-0 not cached rollup at version 0.25.4, downloading...
    node-0 Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80

Because Rollup 0.25.4 was published after I last installed, but I'm offline, so I don't have 0.25.4.

**Comment by nolanlawson** [comment]
Related: https://github.com/nolanlawson/local-npm/issues/102
