### ISSUE TITLE
Crash on timeout errors when on slow connection

### ISSUE THREAD

**Issue by DrorT** [nolanlawson/local-npm#104]
Hey,
The package is great and helps a lot especially on very slow connections, but on big installs local-npm will crash a few times as a result of Timeouts with the following error - 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 199.27.79.162:443
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

In cases like this 'npm install' will keep on running and restarting local-npm will allow for it to continue installation. But unless I am watching local-npm I sometimes miss the crash and the time for install gets longer.

Changing the way local-npm works to issue a warning but continue retrying will be a fix for this.

Thanks

**Comment by nolanlawson** [comment]
05062069bb1444d2f277d045c1372f6ca6e1d6a0
