### ISSUE TITLE
Publish private modules locally

### ISSUE THREAD

**Issue by adius** [nolanlawson/local-npm#107]
It would be great if it was possible to publish a private repository to local-npm. I.e. when `private: true` is set in package.json and one runs `npm publish` it will no be published to npm but it still can be installed locally via local-npm.

**Comment by nolanlawson** [comment]
I thought about it and decided I don't think it's within scope for what I want local-npm to do. However it's entirely possible to build your own local npm using PouchDB, so I encourage anybody to look at the code and try. :)

**Comment by nolanlawson** [comment]
Reason being: it's a whole lot of work to fully support a writable npm-compatible API, as opposed to just mirroring npm.
