### ISSUE TITLE
A user-local version that uses the npm cache as its db?

### ISSUE THREAD

**Issue by iarna** [nolanlawson/local-npm#109]
I wonder if anyone has given any thought to having an entirely user-local version that uses `~/.npm` to store data. With something like that, npm could safely use `--cache-min=Infinity` and avoid even talking to the proxy unless it needed something not cached.

It looks like this will just involve hooking the `pouchdb` changes feed to update metadata and making it possible to swap out `leveldb` for something that talks to the npm cache.

Thoughts? Would you all be interested in this as a PR?

**Comment by nolanlawson** [comment]
This has been proposed elsewhere, but I've said I think that's out of scope for local-npm. However local-npm can be used as a nice springboard for anybody looking to implement such a thing (i.e. basically a Sinopia on top of PouchDB).
