### ISSUE TITLE
markdown compatibility

### ISSUE THREAD

**Issue by millette** [nolanlawson/local-npm#110]
I was looking at <http://127.0.0.1:5080/_browse/#/local-npm> and the "How it works" section tells of the <http://127.0.0.1:16984/_utils> entry point - but because the markdown parser used seems a little bit flaky (I haven't investigated any further yet) the url <http://127.0.0.1:16984/utils> is shown instead with a bit in italic (because of the two underline characters. Compare the output with <https://github.com/nolanlawson/local-npm#how-it-works>. This is just one example.

What markdown library is used in the deps? Perhaps a bit of config can fix its output.

**Comment by nolanlawson** [comment]
The markdown library is [this one](https://github.com/nolanlawson/local-npm/blob/master/lib/www/scripts/deps/markdown.min.js); I admit I don't recall exactly which one it is. Pull requests to improve it would be accepted. :)

**Comment by wmhilton** [comment]
fixed in #125
