### ISSUE TITLE
Github packages not cached?

### ISSUE THREAD

**Issue by nrutman** [nolanlawson/local-npm#124]
I love this project. But I do have a question: most of my packages are from npm, but a few are from Github...via something like this in `dependencies`:

```
"angular-ui-bootstrap": "git+https://github.com/angular-ui/bootstrap-bower.git#1.3.1"
```

Is there a way for `local-npm` to cache these requests as well? Right now, these requests are still trying to fetch from Github, making an offline install impossible.

Any ideas? Thanks!

**Comment by nolanlawson** [comment]
Sorry, no, there is no way. By design it's supposed to always fetch the latest version from Git.

**Comment by nrutman** [comment]
@nolanlawson, yeah, I didn't know if this was a possibility or not. Thanks for the reply.
