### ISSUE TITLE
Does not sync react-measure@0.5.0

### ISSUE THREAD

**Issue by despairblue** [nolanlawson/local-npm#126]
![screenshot from 2016-08-12 11-28-43](https://cloud.githubusercontent.com/assets/927609/17618449/227bda50-6080-11e6-94b4-97df2cff36ed.png)

Happens on my computer and on our CI server.

**Comment by wmhilton** [comment]
I'm having similar trouble. I noticed just a few days ago that the 'now' package is out of sync. (Only noticed because when I tried running it, it refused, saying to update to the latest version.)

```
$ npm --registry=https://registry.npmjs.org/ info now version
0.21.1
$ npm --registry=https://registry.node-modules.io/ info now version
0.19.0
```

@nolanlawson is there a quick and dirty solution to making local-npm loose its cache for these modules?

**Comment by wmhilton** [comment]
Is this related to #2?
p.s. I know this module is officially un-maintained as of #122. Let me know if you'd rather I start a fork than make a pull request if I figure this one out.

@despairblue are you using local-npm in a hobbiest or a company setting? I thought I was the only one crazy enough to keep using this module :)

**Comment by nolanlawson** [comment]
@wmhilton No, you would have to stop local-npm, delete its files, and restart it.

This bug should have been solved in the latest version of PouchDB. If you're still running into it, then that's very troubling.

**Comment by despairblue** [comment]
@wmhilton 

We went back to use `npm --cache-min=Infinity` since works reliably with the latest npm. I don't have the resources at the moment investigate this properly or fix it, since it does not affect me anymore nor the company that I work for.

But we did use it in production and it worked fine otherwise :smiley:

**Comment by wmhilton** [comment]
@nolanlawson Alrighty, I cleared out the directory, let it re-sync, and now it sees the updated package version. Maybe it won't happen ever again! :grinning: Certainly don't let it trouble you.

**Comment by wmhilton** [comment]
@despairblue Can you try stopping local-npm, deleting the data files, and restarting it? Or do you not have it running anymore? I'm just wondering if it's safe to mark this resolved.

**Comment by despairblue** [comment]
@wmhilton I removed it locally and from out CI server, sry :disappointed:
