### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by DanielRuf** [nolanlawson/local-npm#181]
The last release was about two years ago.
https://github.com/local-npm/local-npm/compare/2.2.2...master

## Detailed Description

We could need a new release with the fixes and green tests.

**Comment by gabrielcsapo** [comment]
I am working on this, trying to prioritize my day job 😄

**Comment by gabrielcsapo** [comment]
please look at the project https://github.com/local-npm/local-npm/projects/1 to see what is currently being worked on.

**Comment by gabrielcsapo** [comment]
Just an update, I have a passing build running locally, going to push it to a beta branch tomorrow if you are interested in testing @DanielRuf ?

**Comment by DanielRuf** [comment]
Hi @gabrielcsapo,

I can try to invest some time to do some tests.

**Comment by DanielRuf** [comment]
Hi @gabrielcsapo,

thanks.

I can try to invest some time to do some tests.

**Comment by manuelbieh** [comment]
Any news on that? I'm getting an error `prebuild-install WARN install No prebuilt binaries found (target=12.4.0 runtime=node arch=x64 platform=win32)` when I try to install it on my Windows machine.

**Comment by DanielRuf** [comment]
Hi @manuelbieh,

Which exact error do you get? At least this is just a warning.

**Comment by gabrielcsapo** [comment]
I have this weekend free will get a release out by Sunday night at the latest. Sorry everyone.

**Comment by gabrielcsapo** [comment]
Working on this now, if I can't get a beta out tonight I am on call tomorrow and I will have some downtime during the day. It doesn't help I don't own a laptop anymore other than my work one :( _scouring eBay for a good deal_

**Comment by DanielRuf** [comment]
No problem, thanks for taking the time =)
