### ISSUE TITLE
Starts re-replicating from scratch sometimes

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/local-npm#45]
@remy For the record, I am still seeing this sometimes. Happened a moment ago when my laptop went into hibernate mode and then restarted; might be related. Still, since the checkpoint is stored on disk, there's no reason it should start re-replicating from scratch.

```
...
local-npm-0 Replicating skimdb, last_seq is: 35869 (18.74%)
local-npm-0 Replicating skimdb, last_seq is: 36071 (18.84%)
local-npm-0 Replicating skimdb, last_seq is: 36271 (18.95%)
local-npm-0 Replicating skimdb, last_seq is: 36472 (19.05%)
local-npm-0 Replicating skimdb, last_seq is: 36674 (19.16%)
local-npm-0 Replicating skimdb, last_seq is: 36875 (19.26%)
local-npm-0 Replicating skimdb, last_seq is: 37076 (19.37%)
local-npm-0 Replicating skimdb, last_seq is: 37276 (19.47%)
local-npm-0 Replicating skimdb, last_seq is: 37476 (19.58%)
local-npm-0 Replicating skimdb, last_seq is: 37677 (19.68%)
local-npm-0 Replicating skimdb, last_seq is: 37877 (19.78%)
local-npm-0 Replicating skimdb, last_seq is: 38077 (19.89%)
local-npm-0 Replicating skimdb, last_seq is: 38277 (19.99%)
local-npm-0 Replicating skimdb, last_seq is: 38478 (20.1%)
```

**Comment by rex** [comment]
@nolanlawson I apologize for bumping an old thread but I installed `local-npm` earlier (amazing, by the way! Thank you!) and upon following the instructions detailed in the provided gist for creating a `LaunchAgent` on Mac it started re-replicating the entire skimdb. I noticed that it was a bit weird that the Fauxton UI showed the entire DB size as ~70MB, and checked `pm2 logs` and sure enough, replicating. 

I'm guessing this isn't intended behavior... Would you like me to create a separate issue with the context of setting it up as a `LaunchAgent`?

**Comment by nolanlawson** [comment]
Nah, this issue is fine. Still trying to reproduce it, though. I use a LaunchAgent myself on my own laptop, and I haven't seen this bug in months. :/

**Comment by rex** [comment]
I feel your pain. People make fun of it, but "it works on my machine" is often just the way it is. 

I'll try unloading and reloading the LaunchAgent and see if it restarts replicating skimdb.

**Comment by nolanlawson** [comment]
I honestly don't understand what the difference is if you run it as a LaunchAgent, but it seems like a file/permissions thing to me? Maybe when it runs as a LaunchAgent the files are saved with a particular set of permissions, and then those don't transfer over when you run it normally?

To test, you can try running `local-npm` _only_ in regular mode (without the LaunchAgent), and I guarantee it will not start re-replicating from scratch. The way it works is that it writes checkpoints to the local PouchDB database, so as long as it has access to that checkpoint file, it should work fine. Also: keep in mind that LevelDB databases can't be accessed by more than one Node.js process, so trying to run 2 at once could cause unexpected behavior...

**Comment by rex** [comment]
I am not sure what the difference would be either. Now that you mention it, though, I did have a facepalm moment when I realized the mistake I made in my initial investigation. 

`local-npm` stores the PouchDB database **in the current working directory from which it is executed**. 

I noticed this when I saw `pouch__all__dbs__` and `pouch__all__sessions__` in a git diff and realized immediately that it was the directory I ran `local-npm` from while testing. I located the directory I originally ran `local-npm` from, ran it again, and....

<img width="508" alt="screenshot 2016-01-21 10 29 47" src="https://cloud.githubusercontent.com/assets/4247754/12487026/fc085cd6-c02a-11e5-9701-b6c6b7181b89.png">

Boom. Picked right back up. 

So it seems to me the answer is just education-via-readme. Wherever you run `local-npm` first, *that place* is where the data is stored and thus becomes the directory it needs to be run from in the future. 

That being said, though, if there was a way to standardize the PouchDB install location then a user could run `local-npm` from any directory on the machine and it would never duplicate the database.

**Comment by nolanlawson** [comment]
Ah, didn't realize that was the issue. Yeah, I would ultimately like to create a `brew install local-npm` that just creates the LaunchAgent and chooses a canonical storage location, but looking through the Homebrew docs, it seems pretty unfeasible because they only allow "high profile" software (and don't typically accept patches submitted by the software author themselves). But maybe a bash script run with `sudo` would work just as well.

**Comment by rex** [comment]
@nolanlawson I just saw https://github.com/nolanlawson/local-npm-launch-agent and felt compelled to come back to this issue and let you know how awesome I feel your solution is. Not only is it incredibly simple for new `local-npm` users but it solves a myriad of other issues by guaranteeing a standardized install location. 

10/10 well done.

:beers: :tada:

**Comment by nolanlawson** [comment]
Awesome, glad it works for you! :)
