### ISSUE TITLE
leveldown dependancy error

### ISSUE THREAD

**Issue by pacav69** [nolanlawson/local-npm#48]
i get an error when i try to install on a windows 7 computer

C:\temp\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown>if not defined npm_config_node_gyp (n
ode "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
s" rebuild )  else (node  rebuild )
C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py:883: Warning: 'as' w
ill become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 11, in <modu
le>
    import gyp
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8,
 in <module>
    import gyp.input
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 883
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gy
p\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
yp.js" "rebuild"
gyp ERR! cwd C:\temp\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing leveldown@0.10.5
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\
\bin\\npm-cli.js" "install" "local-npm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.

**Comment by nolanlawson** [comment]
Yeah, unfortunately LevelDOWN does not compile properly on Windows. It is a known issue: https://github.com/Level/leveldown/issues/207

**Comment by pacav69** [comment]
i managed to get local-npm running by updating to the latest version of npm
apparently the msi version on nodejs is outdated
so you have to use version v2.7 of python and setting npm to use, then run
the install.sh from nodejs to update
then did an install of local-npm and it is now working

On Sat, Aug 29, 2015 at 9:42 AM, Nolan Lawson <notifications@github.com>
wrote:

> Closed #48 <https://github.com/nolanlawson/local-npm/issues/48>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolanlawson/local-npm/issues/48#event-395610843>.
>



-- 
Paul Cavanagh
Business and IT Consultant
+86-13774291848
------------------------------------------------
http://silverpcgroup.com/
Webhosting and Web Development

Dropbox for Android, iPhone and file sharing
http://db.tt/664PP2JA

For those with smartphones you can scan the QR Code
Paul Cav QR Code
<https://docs.google.com/drawings/d/1gaMyNmCjS1MeiTd8qhX2BU46txJG7N7gDrNCKgJorC0/edit>
