### ISSUE TITLE
installation problem under node v4.0.0 and npm v2.14.3

### ISSUE THREAD

**Issue by vbauerster** [nolanlawson/local-npm#49]
After updating to node 4, local-npm ceased to work at some point.
Uninstall was ok, but when ```npm install -g local-npm```, I got [this error](https://drive.google.com/file/d/0ByRz5v9LmStMczZVd3dITnVpV2M/view?usp=sharing).
Here is [npm-debug.log](https://drive.google.com/file/d/0ByRz5v9LmStMVkVGUjZyUHZGTEk/view?usp=sharing) file.

**Comment by nolanlawson** [comment]
I can repro. Seems to be related to out-of-date leveldown packages.

**Comment by nolanlawson** [comment]
Should be fixed in 1.4.5, thanks for reporting!

**Comment by vbauerster** [comment]
Indeed fixed) Thanks for quick update!
