### ISSUE TITLE
Doesn't work with scoped npm modules

### ISSUE THREAD

**Issue by jimpick** [nolanlawson/local-npm#50]
Here's an example of the error from `npm install`:

```
npm ERR! 404 Not found : @jimpick/spectacle
npm ERR! 404 
npm ERR! 404 '@jimpick/spectacle' is not in the npm registry.
```

Information on scoped (and private) modules:

https://docs.npmjs.com/getting-started/scoped-packages

**Comment by nolanlawson** [comment]
Interesting! I'm not really sure how to get this to work, though, since I guess the modules are published in a separate registry? local-npm works by replicating the main registry to a local pouchdb; not sure which registry would need to be replicated for private modules.

**Comment by jimpick** [comment]
I found some docs here:

https://github.com/npm/npm/blob/master/doc/misc/npm-scope.md

It looks like I can set a registry per-scope, so I can do this:

npm config set @jimpick:registry https://registry.npmjs.org

So I can still use local-npm for the majority of packages, and npm will use the official registry for scoped packages. Nice!

**Comment by gr2m** [comment]
fyi while scoped packages are not synced because they are not listed in the registry changes, I had no issues with them, they got installed from the main registry without the necessity to manually adjust any settings with `npm config set`

**Comment by nolanlawson** [comment]
yeah, what's "supposed" to happen is that scoped modules are just fetched using the fallback functionality. (I.e. the app assumes it hasn't synced them yet and fetched from remote.) I would actually be surprised if it _didn't_ work; not sure what happened in your case @jimpick. (N.B.: I don't use scoped packages myself.)

**Comment by gr2m** [comment]
yeah, I think that’s exactly how it works for me :+1:

**Comment by nolanlawson** [comment]
Cool, so maybe this was some other bug that's now resolved? @jimpick can you reopen this if it's still an issue? Thanks!

**Comment by elgubenis** [comment]
do one has to wait until the skimdb replication is complete so it sees that private scoped packages does not get fetches? or should it already work while still recplicating?

**Comment by elgubenis** [comment]
would be nice though to also have a way to cache scoped packages, but no idea how.

**Comment by nolanlawson** [comment]
It should work with scoped packages both during and after skimdb replication, but I haven't tested it.
