### ISSUE TITLE
Ability to specify a working directory

### ISSUE THREAD

**Issue by WoodyWoodsta** [nolanlawson/local-npm#56]
Would be great to be able to pass a directory in which the db and other files will be made, so that we do not have to invoke `local-npm` in the directory where we want the files. This would help a lot with tools like forever.

**Comment by nolanlawson** [comment]
fixed in 1.5.0 via https://github.com/nolanlawson/local-npm/pull/55. Thanks!

**Comment by WoodyWoodsta** [comment]
Oh brilliant... Thanks for the incredible tool btw :+1:
