### ISSUE TITLE
publish not working unless you're already logged in

### ISSUE THREAD

**Issue by mattkrick** [nolanlawson/local-npm#77]
NPM@3.5.3

first time running publish i get `ENEEDAUTH`
run `npm adduser`
fill out stuff
get the following 
```
npm ERR! Unexpected token C
npm ERR! Cannot PUT /-/user/org.couchdb.user:mattkrick
```

currently switching back whenever i need to publish, which isn't great, but sure beats the heck out of waiting 5 mins to run install thanks to npm3  :+1:

**Comment by nolanlawson** [comment]
Yeah, currently `npm publish` only works if you are _already_ logged in. This is something worth fixing, though! :)

**Comment by gera2ld** [comment]
Same issue here, and `npm login` not work either (got error messages the same as above).
Do I have to switch my registry back to `https://registry.npmjs.org` to log in?

**Comment by nolanlawson** [comment]
@gera2ld What I've normally done is `npm login` in one registry, then copy the `.npmrc` credentials from one to the other when I switch back. Of course you shouldn't have to do that, but in the meantime, it's a workaround.

**Comment by nolanlawson** [comment]
So now that we have tests in place, this should be a fairly easy issue to reproduce. You would just need to add a test for `npm login` and confirm that the app at least redirects you to the main npm (no need to expose your credentials in the test itself, just reproduce a 403 or something...).

**Comment by nolanlawson** [comment]
Fixed by https://github.com/nolanlawson/local-npm/pull/95.
