### ISSUE TITLE
Npm always trying to install from http://127.0.0.1:5080 for certain packages

### ISSUE THREAD

**Issue by cbrwizard** [nolanlawson/local-npm#89]
Hey, I have a problem that after using local-npm some packages are always trying to get installed from http://127.0.0.1:5080 even though I have `npm config get registry` = `https://registry.npmjs.org/`. I've tried running `npm cache clean` but no luck. What can I do?

**Comment by nolanlawson** [comment]
Hmmm, that's weird, `npm cache clear` should fix that issue. :( Have you tried `rm -fr node_modules` as well?

The reason this is happening is that `local-npm` overrides the package metadata to point to localhost:5080, but really it shouldn't continue to use those URLs if you `npm cache clean`. You might try a `npm config set loglevel verbose` as well.

**Comment by cbrwizard** [comment]
Thanks for a quick answer!
Actually it was my mistake: I forgot to delete a npm-shrinkwrap file with an old http://127.0.0.1:5080 address, that's why it continued to use it for certain packages. I will remember it from now on [:

**Comment by skelso01** [comment]
I know this Task is closed, but I installed local-npm and get the error on build machines, which uses the local-npm Server in our Network. First it works fine. But after half a day I got this problem. Can anybody help me to get this work?
