### ISSUE TITLE
Can't use when offline

### ISSUE THREAD

**Issue by rahmatawaludin** [nolanlawson/local-npm#96]
It seems I haven't read much about how to use this tools. So, I were following Addy Osmani article https://addyosmani.com/blog/using-npm-offline. I run with `local-npm -d ~/.local-npm` then I follow this guide:

- Check your network connection is up
- Run an npm install to grab a module or collection of dependencies from a package.json file. For example, lodash.
- At this point, local-npm will have a cached version of these modules stored
- Clear the npm cache using npm cache clean or delete the modules from your node_modules directory
- Turn off your wifi/kill your network connection
- Try running that npm install again. Everything should install correctly through the local-npm cache without hitting the network at all

When I turn off my wifi, I got this..

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

If I start `local-npm` when I'm offline, I got this message..

```
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com skimdb.npmjs.com:443
Error fetching info() from https://skimdb.npmjs.com/registry, retrying after 1100 ms...
```

And when I try to install a package.. 

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

Then `local-npm` just stopped. 

Is this the correct behaviour? 
I thought it should be working when I'm offline. 

Thanks.

**Comment by nolanlawson** [comment]
`local-npm` takes a little while to sync all metadata from the remote registry. This metadata is required in order to function entirely offline, and it's not cached when you simply `npm install`.

On a fast connection, it should finish replication in about an hour. On a slower connection, it might take a few hours. You can check the logs to see when it's done (it'll say "100%").

**Comment by nolanlawson** [comment]
That said, caching the metadata optimistically would be a nice feature, so I might add it. :)

**Comment by rahmatawaludin** [comment]
Ah.. this clear my confusion. Could you tell me how large is the metadata file?

**Comment by nolanlawson** [comment]
On my machine, it's about 765MB.

**Comment by mattkrick** [comment]
If I start local-npm with an internet connection & then go offline, everything works fine.

If I start up local-npm when I'm offline, I get the following error:
```
Error: getaddrinfo ENOTFOUND skimdb.npmjs.com skimdb.npmjs.com:443
Error fetching info() from https://skimdb.npmjs.com/registry, retrying after 1949 ms...
```

Is there a workaround?

**Comment by nolanlawson** [comment]
If you go offline and then go back online, it will retry. At least, I have tests in place that verify that, so that is how it ought to work.

**Comment by mattkrick** [comment]
that's true, but here's the use case:

Step on a plane with the intent of switching a package to use immutable-js
Go to install immutable-js, but I'm offline
Open local-npm, install immutable-js

As a workaround, I currently have to search locally for immutable-js, copy & paste it, get some missing dependency errors, copy those, etc etc until npm can successfully walk the whole dependency tree.

**Comment by nolanlawson** [comment]
Yeah, I've been trying to think of how to support use cases like this. I'm sure some people would be happy if local-npm just automatically downloaded the top _n_ npm modules and kept them continually up-to-date, but I've shied away from that because I felt it was too aggressive for the common use case. (See my ideas in https://github.com/nolanlawson/local-npm/issues/102). It may still be possible via a command-line flag, though.

**Comment by mattkrick** [comment]
i like the command-line flag idea. i pass in a flag & i don't care if i
don't have the latest version.

**Comment by mattkrick** [comment]
also, this would save a ton of time on those 304s (on a slow connection,
this can approach 1 minute per 304)
