### ISSUE TITLE
Allow specifying replication batch size in command line

### ISSUE THREAD

**Issue by forivall** [nolanlawson/local-npm#98]
Especially for syncing local-npm between different computers ("protip: You can replicate from your friend's local-npm..."), it would be nice to increase the batch size, unless there's some other limitation that forbids this.

Or, batch size could be automatically increased if you detect that the remote address is on a local subnet (192.168.x.x / 10.x.x.x / that other local subnet that nobody uses)

**Comment by nolanlawson** [comment]
If there's a more ideal batch size, I think it should just be increased across the board. Batch size in PouchDB/CouchDB is best determined based on the average size of documents. So if you see better performance from your friend's computer at x number of documents, then most likely you'd get the same benefit from syncing from npm remote.

And to be fair, I basically pulled the current batch size out of a hat. :stuck_out_tongue: So I wouldn't be surprised if there's a better one. Which one works best for you?

**Comment by forivall** [comment]
I got the chance to test it, and it turns out that your guess was perfect :neutral_face: . My test code is here: https://github.com/forivall/local-npm/tree/replication-pref-test
